// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: products/v1/events/events.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED EventType = 0
	EventType_EVENT_TYPE_CREATED     EventType = 1
	EventType_EVENT_TYPE_DELETED     EventType = 2
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_TYPE_CREATED",
		2: "EVENT_TYPE_DELETED",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED": 0,
		"EVENT_TYPE_CREATED":     1,
		"EVENT_TYPE_DELETED":     2,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_products_v1_events_events_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_products_v1_events_events_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_products_v1_events_events_proto_rawDescGZIP(), []int{0}
}

type ProductEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          EventType              `protobuf:"varint,3,opt,name=type,proto3,enum=products.v1.events.EventType" json:"type,omitempty"`
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductEvent) Reset() {
	*x = ProductEvent{}
	mi := &file_products_v1_events_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductEvent) ProtoMessage() {}

func (x *ProductEvent) ProtoReflect() protoreflect.Message {
	mi := &file_products_v1_events_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductEvent.ProtoReflect.Descriptor instead.
func (*ProductEvent) Descriptor() ([]byte, []int) {
	return file_products_v1_events_events_proto_rawDescGZIP(), []int{0}
}

func (x *ProductEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductEvent) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *ProductEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

var File_products_v1_events_events_proto protoreflect.FileDescriptor

const file_products_v1_events_events_proto_rawDesc = "" +
	"\n" +
	"\x1fproducts/v1/events/events.proto\x12\x12products.v1.events\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa2\x01\n" +
	"\fProductEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x121\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1d.products.v1.events.EventTypeR\x04type\x12;\n" +
	"\voccurred_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt*W\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12EVENT_TYPE_CREATED\x10\x01\x12\x16\n" +
	"\x12EVENT_TYPE_DELETED\x10\x02B\x1eZ\x1cguru/apis/products/v1/eventsb\x06proto3"

var (
	file_products_v1_events_events_proto_rawDescOnce sync.Once
	file_products_v1_events_events_proto_rawDescData []byte
)

func file_products_v1_events_events_proto_rawDescGZIP() []byte {
	file_products_v1_events_events_proto_rawDescOnce.Do(func() {
		file_products_v1_events_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_products_v1_events_events_proto_rawDesc), len(file_products_v1_events_events_proto_rawDesc)))
	})
	return file_products_v1_events_events_proto_rawDescData
}

var file_products_v1_events_events_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_products_v1_events_events_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_products_v1_events_events_proto_goTypes = []any{
	(EventType)(0),                // 0: products.v1.events.EventType
	(*ProductEvent)(nil),          // 1: products.v1.events.ProductEvent
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_products_v1_events_events_proto_depIdxs = []int32{
	0, // 0: products.v1.events.ProductEvent.type:type_name -> products.v1.events.EventType
	2, // 1: products.v1.events.ProductEvent.occurred_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_products_v1_events_events_proto_init() }
func file_products_v1_events_events_proto_init() {
	if File_products_v1_events_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_products_v1_events_events_proto_rawDesc), len(file_products_v1_events_events_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_products_v1_events_events_proto_goTypes,
		DependencyIndexes: file_products_v1_events_events_proto_depIdxs,
		EnumInfos:         file_products_v1_events_events_proto_enumTypes,
		MessageInfos:      file_products_v1_events_events_proto_msgTypes,
	}.Build()
	File_products_v1_events_events_proto = out.File
	file_products_v1_events_events_proto_goTypes = nil
	file_products_v1_events_events_proto_depIdxs = nil
}
